#!/bin/sh
#
# Simple cron script - save the current clock periodically in case of
# a power failure or other crash

# Systems running systemd use the systemd timer unit.
[ -d /run/systemd/system ] && exit 0

if (command -v fake-hwclock >/dev/null 2>&1) ; then
  fake-hwclock save
fi
